Правда или действие (часть 1)
htmlacademy-javascript/453981-keksobooking-27 pull request #7
Opened 2022-11-13 23:16 UTC by nothingissafefck

2022-11-14 07:19 UTC, pavel-nyukalo requested changes

2022-11-14 07:19 UTC, pavel-nyukalo commented on js/form.js
> +const validator = new Pristine(adForm);
Насколько помню, пристину надо еще указать куда ему вставлять сообщение об ошибке, сейчас в опубликованной версии валидация как бы работает, но не пишет где что надо поправить в полях

2022-11-14 07:19 UTC, pavel-nyukalo commented on js/form.js
> +const ROOM_NUMBER_CAPACITIES = {
Это у нас константа - поэтому по критерию ее надо в начало модуля, сразу после импорта, но перед основным кодом

2022-11-14 07:19 UTC, pavel-nyukalo commented on js/form.js
> +});
Еще нам нужны подсказки насчет полей, которые не валидируются пристином.
Два варианта:
1. валидировать пристином (можно даже просто атрибутами в разметке, тогда надо будет его в `index.html` подключить)
2. Не отменять действие по-умолчанию, чтобы браузер сам по атрибутам провалидировал (например, что это обязательное поле, и его длину если надо)

2022-11-14 19:09 UTC, nothingissafefck commented on js/form.js
> +});
А зачем подключать еще раз в `index.html`? Атрибуты в разметке есть там где надо по ТЗ, пристин подключен в `form.js`, валидация работает

2022-11-16 09:32 UTC, pavel-nyukalo approved these changes

2022-11-16 09:32 UTC, merged